spring:
  application:
    name: eurekaserver

  profiles:
    active: prod
  config:
    import: optional:configserver:http://localhost:8071
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url: http://eurekaserver:8761/eureka/


